before_script:
    - mkdir travis-overlay
    - mv !(travis-overlay) travis-overlay/
    - mv .* travis-overlay
    - wget "http://distfiles.gentoo.org/distfiles/portage-2.2.10.tar.bz2"
    - wget "http://distfiles.gentoo.org/snapshots/portage-latest.tar.xz"
    - mkdir -p portage tree
    - sudo chmod 777 /usr
    - sudo chmod -R 777 /etc/
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - mkdir -p /etc/portage /usr/portage/distfiles
    - tar xjf portage-2.2.10.tar.bz2 -C portage
    - tar xJf portage-latest.tar.xz -C /usr/
    - cp portage/portage-2.2.10/cnf/repos.conf /etc/portage/

script: 
    - cd travis-overlay
    - "./../portage/portage-2.2.10/bin/repoman full -d"

